baseURL = 'https://clienk.com'
languageCode = 'en-us'
title = 'Clienk.com'

DefaultContentLanguage = "en"

[taxonomies]
  tag = "tags"
  category = "categories"
  year = "year"
	month = "month"

[outputs]
    home = [ "HTML", "JSON", "RSS"]