# main menu
[[main]]
name = "Home"
url = "/zh/"
weight = 1

[[main]]
name = 'Resturants'
url = '/zh/resturants'
weight = 2

[[main]]
name = "About"
url = "/zh/about"
weight = 3

[[main]]
name = "Blog"
url = "/zh/blog"
weight = 4