# main menu
[[main]]
name = "呼叫中心"
url = "/zh/contact-center"
weight = 1

[[main]]
name = '客服教练'
url = '/zh/agent-coach'
weight = 2

[[main]]
name = "报告"
url = "/zh/real-time-reporting"
weight = 3

[[main]]
name = "客户分析"
url = "/zh/customer-profiling"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5
