# main menu
[[main]]
name = "呼叫中心"
url = "/contact-center"
weight = 1

[[main]]
name = '客服教练'
url = '/agent-coach'
weight = 2

[[main]]
name = "报告"
url = "/real-time-reporting"
weight = 3

[[main]]
name = "客户分析"
url = "/customer-profiling"
weight = 4

[[main]]
name = "Blog"
url = "/blog"
weight = 5

# footer menu left
[[footer_left]]
name = "主页"
url = "/"

[[footer_left]]
name = "呼叫中心"
url = "contact-center"

[[footer_left]]
name = "客服教练"
url = "agent-coach"

[[footer_left]]
name = "报告"
url = "real-time-reporting"

[[footer_left]]
name = "客户分析"
url = "customer-profiling"

# footer menu right
[[footer_right]]
name = "关于CLIENK"
url = "about-clienk"

[[footer_right]]
name = "联系我们"
url = "contact-us"

[[footer_right]]
name = "隐私政策"
url = "privacy-policy"