languageCode = 'en'
defaultContentLanguage = 'en'
baseURL = 'https://clienk.com'

[params]
    dateFormat = "02 Jan 2006"

#################### default parameters ################################

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content/english"
    flag = "en_gb.gif"
    weight = 1

  [languages.zh]
    languageName = "曼陀林"
    contentDir = "content/zh"
    flag = "zh_cn.gif"
    weight = 2
    
  [languages.en.params]
    footer_subtitle = "One single AI-powered contact center for all your customer care."
    footer_title = "A BETTER WAY TO ENGAGE AND RETAIN YOUR CUSTOMERS." 
    footer_copy = "© 2003-2023 Clienk - All Rights Reserved"
    footer_icp_txt = ""
    footer_icp_link = ""
    footer_address = "Hong Kong <br> Shanghai <br> Singapore"
    btn = "Request A Demo"
    btn_link = "request-a-demo"
    
  [languages.zh.params]
    footer_subtitle = "人工智能驱动的联系中心，为您的所有客户服务提供支持。"
    footer_title = "一个更好的方式去吸引和留住客户"
    footer_copy = "© 2003-2023 Clienk - 保留所有权限 "
    footer_icp_txt = ""
    footer_icp_link = ""
    footer_address = "香港 <br> 上海 <br> 新加坡"
    btn = "寻求演示"
    btn_link = "request-a-demo"
    
[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.75

[taxonomies]
  category = 'categories'
  tag = 'tags'