#################### default parameters ################################
[languages]
  [languages.en]
  languageName = "English"
  flag = "en_gb.gif" 
  weight = 1

[languages.zh]
  languageName = "曼陀林"
  flag = "zh_cn.gif" 
  weight = 2
